server:
  port: 8090

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finance?useUnicode=true&characterEncoding=utf-8
    username: nature
    password: dy051.
  data:
    redis:
      host: 127.0.0.1
      port: 3680
